/*
版本信息:1.0
创建者	:XYU
功能描述:投资者数_按年龄分类
加载类型:全量加载
源		 表：
	NSODATA.CSDC_INTG_UAP_SEC_ACCT -- 统一账户平台证券账户表
	NSPDATA.ACT_STK_INVST_CLSF_HIS -- 股票投资者分类表
目	标	表:	nsPubMart.CMSC_INVST_CNT_AGE	-- 投资者数_按年龄分类
频		 度:M:月
创建日期:	2018-01-24
修改历史:
修改人	修改日期	修改内容
*/

DELETE FROM ${NSPUBMART}.CMSC_INVST_CNT_AGE
WHERE TJRQ = SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6)
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO ${NSPUBMART}.CMSC_INVST_CNT_AGE
SELECT 
SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6) AS TJRQ
,T1.CLSF_2_AGE AS TZZFL
,T1.TZZSL AS TZZSL
,T1.TZZSL/CAST(T2.TZZZS AS DECIMAL(30,4)) AS TZZSLZB
FROM
(
SELECT b.CLSF_2_AGE, COUNT(DISTINCT a.OAP_ACCT_NBR) AS TZZSL
FROM 
	(SELECT	oap_acct_nbr
	FROM	${NSOVIEW}.CSDC_INTG_UAP_SEC_ACCT	---统一账户平台证券账户表
	WHERE	s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND	e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND	SEC_ACCT_SORT IN ('11','12','14','15','21','22','24')
	  AND	SEC_ACCT_STS  NOT IN ('03','04')
	GROUP BY 1
	 ) a
INNER JOIN	
	(SELECT	oap_acct_nbr	--一码通账户号码
			,CLSF_2_AGE		--二级分类年龄
	FROM	${NSPVIEW}.ACT_STK_INVST_CLSF_HIS	---股票投资者分类表
	WHERE	s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND	e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND CLSF_1 = '1000'
	GROUP BY 1,2
	) b 
	ON a.oap_acct_nbr = b.oap_acct_nbr
GROUP BY 1
) T1,
(
SELECT COUNT(DISTINCT a.OAP_ACCT_NBR) AS TZZZS
FROM 
	(SELECT	oap_acct_nbr
	FROM	${NSOVIEW}.CSDC_INTG_UAP_SEC_ACCT	---统一账户平台证券账户表
	WHERE	s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND	e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND	SEC_ACCT_SORT IN ('11','12','14','15','21','22','24')
	  AND	SEC_ACCT_STS  NOT IN ('03','04')
	GROUP BY 1
	 ) a
INNER JOIN	
	(SELECT	oap_acct_nbr	--一码通账户号码
			,CLSF_2_AGE		--二级分类年龄
	FROM	${NSPVIEW}.ACT_STK_INVST_CLSF_HIS	---股票投资者分类表
	WHERE	s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND	e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	  AND CLSF_1 = '1000'
	GROUP BY 1,2
	) b 
	ON a.oap_acct_nbr = b.oap_acct_nbr
) T2
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT


