/*
版本信息:1.0
创建者	:XYU
功能描述:投资者交易量_按持股市值分类
加载类型:全量加载
源		 表：
	NSPUBMART.KPI_STK_TRAD_BY_INVST_IDSTR -- 股票成交情况(投资者及行业)
目	标	表:	nsPubMart.CMSC_FUTRS_INVST_CNT_HLD_MKT_VAL	-- 投资者交易量_按持股市值分类
频		 度:M:月
创建日期:	2018-01-24
修改历史:
修改人	修改日期	修改内容
*/

DELETE FROM ${NSPUBMART}.CMSC_FUTRS_INVST_CNT_HLD_MKT_VAL
WHERE TJRQ = SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6)
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO ${NSPUBMART}.CMSC_FUTRS_INVST_CNT_HLD_MKT_VAL
SELECT
SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6) AS TJRQ
,T1.STK_INVST_SORT AS TZZFL
,T1.CJSL
,T1.CJSL/T2.CJZS AS CJSJZB
FROM
(
	SELECT 
	STK_INVST_SORT 
	,SUM(IDX_VAL) AS CJSL
	FROM ${NSPUBVIEW}.KPI_STK_TRAD_BY_INVST_IDSTR	
	WHERE STAT_DATE BETWEEN (
		SELECT MAX(CALENDAR_DATE) 
		FROM ${NSPVIEW}.PTY_TRAD_CLND
		WHERE CALENDAR_DATE <= ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1)
		AND DAY_OF_MONTH = 1
	) AND 
	(
		SELECT MAX(CALENDAR_DATE)
		FROM ${NSPVIEW}.PTY_TRAD_CLND
		WHERE CALENDAR_DATE < '${TXDATE}'
		AND EOM_SIGN = 1
	)
	AND STK_TYPE = '-1'
	AND LSTN_BORD = '-1'
	AND IC = '-1'
	AND SEC_EXCH_CDE = '-1'
	AND IDX_CDE = 'SK021'
	AND STK_INVST_SORT IN ('1100' ,'1200' ,'1300' ,'1400' ,'1500')
	GROUP BY 1
) T1,
(
	SELECT 
	SUM(IDX_VAL) AS CJZS
	FROM ${NSPUBVIEW}.KPI_STK_TRAD_BY_INVST_IDSTR	
	WHERE STAT_DATE BETWEEN (
		SELECT MAX(CALENDAR_DATE) 
		FROM ${NSPVIEW}.PTY_TRAD_CLND
		WHERE CALENDAR_DATE <= ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1)
		AND DAY_OF_MONTH = 1
	) AND 
	(
		SELECT MAX(CALENDAR_DATE)
		FROM ${NSPVIEW}.PTY_TRAD_CLND
		WHERE CALENDAR_DATE < '${TXDATE}'
		AND EOM_SIGN = 1
	)
	AND STK_TYPE = '-1'
	AND LSTN_BORD = '-1'
	AND IC = '-1'
	AND SEC_EXCH_CDE = '-1'
	AND IDX_CDE = 'SK021'
	AND STK_INVST_SORT IN ('1100' ,'1200' ,'1300' ,'1400' ,'1500')
) T2
WHERE T1.STK_INVST_SORT IS NOT NULL
AND T2.CJZS IS NOT NULL
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT
