/*
版本信息:1.0
创建者	:XYU
功能描述:投资者数_按学历分类
加载类型:全量加载
源		 表：
	NSODATA.CSDC_INTG_SEC_ACCT --CSDC_J0001_整合_证券账户表
目	标	表:	nsPubMart.CMSC_INVST_CNT_EDCT	-- 投资者数_按学历分类
频		 度:M:月
创建日期:	2018-01-24
修改历史:
修改人	修改日期	修改内容
*/

DELETE FROM ${NSPUBMART}.CMSC_INVST_CNT_EDCT
WHERE TJRQ = SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6)
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO ${NSPUBMART}.CMSC_INVST_CNT_EDCT
SELECT 
SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6) AS TJRQ
,T1.EDU_LVL AS TZZFL
,T1.TZZSL AS TZZSL
,T1.TZZSL/CAST(T2.TZZZS AS DECIMAL(30,4) )  AS TZZSLZB
FROM
(
	SELECT
	EDU_LVL
	,COUNT(DISTINCT OAP_ACCT_NBR) AS TZZSL
	FROM 	${NSOVIEW}.CSDC_INTG_SEC_ACCT
	WHERE s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	AND e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	AND SRC_SEC_ACCT_SORT IN ('11','12','14','15','21','22','24')
	AND	SRC_SEC_ACCT_STS  NOT IN ('03','04')
	AND SRC_CUST_SORT IN ('0')
	GROUP BY 1
) T1,
(
	SELECT COUNT(DISTINCT OAP_ACCT_NBR) AS TZZZS
	FROM 	${NSOVIEW}.CSDC_INTG_SEC_ACCT
	WHERE s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	AND e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM ${NSPVIEW}.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
	AND SRC_SEC_ACCT_SORT IN ('11','12','14','15','21','22','24')
	AND	SRC_SEC_ACCT_STS  NOT IN ('03','04')
	AND SRC_CUST_SORT IN ('0')
) T2
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT


